low_level_control:
  low_level_name: CPG_simple
  class: control.low_level_control.cpg_low_level_controller
  params:
    a_dim: ${a_dim}
    num_legs: ${num_legs}
    parameter_dim: 12
    max_frequency: 2
    action_mid_point: ${action_mid_point}
    action_scale: ${action_scale}