seed: 1
robot_type: 'a1'
control_mode: 'position'
tensorType: torch.FloatTensor #torch.cuda.FloatTensor

a_dim: 12
num_legs: 4 
action_mid_point: [0.0, 1.5, -1.8] 
action_scale: [0.8, 2.5, 0.8]

num_trial: 30
episode_length: 500
optimizer: 'cma'

init_parameter:

defaults:
  - low_level_control: CPG_simple
  - reward: velocity_tracking

hydra:
  run:
    dir: ./data/