seed: 1
robot_type: 'a1'
control_mode: 'position'
tensorType: torch.FloatTensor #torch.cuda.FloatTensor

a_dim: 12
num_legs: 4 
action_mid_point: [0.0, 1.5, -1.8] 
action_scale: [1.6, 5.0, 1.6]

num_trial: 1500
episode_length: 1000
optimizer: 'cma'

init_parameter: [1.,         1.,         0.5,        
                0.0, 
                0.0, 0.0, 0.0, 
                0.5, 0.36, 0.833, 
                0.0, 0.0,]


defaults:
  - low_level_control: CPG_simple
  - reward: velocity_tracking

hydra:
  run:
    dir: ./data/${low_level_control.low_level_name}_${reward.reward_name}_${seed}