seed: 2
control_mode: 'position'
tensorType: torch.FloatTensor #torch.cuda.FloatTensor

# low level learning parameters
expert_num: 10
max_train_speed: 0.3

num_timestep_per_HL_action: 100
a_dim: 18
z_dim: 2
max_steps_per_expert: 15
recorded_step_per_expert: 2

#high level dynamics learning params
num_iters: 400
num_steps_per_iter: 25

# evaluation parameters
num_eval_trials: 5
target_reaching_threshold: 0.15
max_eval_steps: 20

data_buffer_capacity: 10000

defaults:
  - env: sim_not_render
  - high_level_control: SAC
  - low_level_control: NN
  - dynamics: sac_policy
  - com_utils: com_utils_RL_vel
  - cost: velocity_tracking

hydra:
  run:
    dir: ./data/${high_level_control.high_level_name}_${low_level_control.low_level_name}_${seed}